# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Duong.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
import csv
from read import read
import os
class Ui_MainWindow(object):
    def on_click(self):
        image = QFileDialog.getOpenFileName(None, 'OpenFile', 'c\\', "Image file(*.jpg)")
        imagePath = image[0]
        pixmap = QPixmap(imagePath)
        self.src_img.setPixmap(pixmap)
        char_result = read(imagePath)
        data = []
        with open('detect_results.csv', "r", encoding="utf-8", errors="ignore") as scraped:
            reader = csv.reader(scraped, delimiter=',')
            for row in reader:
                if row:  # avoid blank lines
                    # row_index += 1
                    columns = [row[0], row[1]]
                    data.append(columns)
        final_line = data[-1]    
        print(final_line)
        _translate = QtCore.QCoreApplication.translate
        character_img = "detect_img/" + final_line[0]
        self.character.setPixmap(QtGui.QPixmap(character_img))
        self.char_result.setText(_translate("MainWindow", str(char_result[2])))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_btn.setGeometry(QtCore.QRect(1020, 630, 331, 40))
        self.load_btn.setObjectName("load_btn")
        self.load_btn.clicked.connect(self.on_click)

        self.label_Bar = QtWidgets.QLabel(self.centralwidget)
        self.label_Bar.setGeometry(QtCore.QRect(1035, 590, 225, 40))
        self.label_Bar.setObjectName("label_Bar")
        self.src_img = QtWidgets.QLabel(self.centralwidget)
        self.src_img.setGeometry(QtCore.QRect(50, 70, 911, 701))
        self.src_img.show()

        self.src_img_label = QtWidgets.QLabel(self.centralwidget)
        self.src_img_label.setGeometry(QtCore.QRect(50, 20, 135, 40))
        self.src_img_label.setObjectName("src_img_label")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(1020, 20, 135, 36))
        self.label_result.setObjectName("label_result")
        # self.label_plate = QtWidgets.QLabel(self.centralwidget)
        # self.label_plate.setGeometry(QtCore.QRect(1020, 65, 135, 36))
        # self.label_plate.setObjectName("label_plate")
        # self.plate = QtWidgets.QLabel(self.centralwidget)
        # self.plate.setGeometry(QtCore.QRect(1020, 105, 135, 36))
        # self.plate.setObjectName("plate")
        
        self.label_char = QtWidgets.QLabel(self.centralwidget)
        self.label_char.setGeometry(QtCore.QRect(1020, 80, 135, 36))
        self.label_char.setObjectName("label_char")
        self.character = QtWidgets.QLabel(self.centralwidget)
        self.character.setGeometry(QtCore.QRect(1020, 105, 500, 400))
        self.character.setObjectName("character")
        self.character.show()
        self.label_char_result = QtWidgets.QLabel(self.centralwidget)
        self.label_char_result.setGeometry(QtCore.QRect(1020, 505, 135, 36))
        self.label_char_result.setObjectName("label_char_result")
        self.char_result = QtWidgets.QTextEdit(self.centralwidget)
        self.char_result.setGeometry(QtCore.QRect(1020, 550, 331, 41))
        self.char_result.setObjectName("char_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        # self.processing_btn.setText(_translate("MainWindow", "Processing"))
        # self.ML_btn.setText(_translate("MainWindow", "Machine Learning"))
        self.label_Bar.setText(_translate("MainWindow", "Control bar"))
        self.src_img_label.setText(_translate("MainWindow", "Src Image"))
        self.label_result.setText(_translate("MainWindow", "Result"))
        # self.label_plate.setText(_translate("MainWindow", "Plate"))
        # self.plate.setText(_translate("MainWindow", ""))
        self.label_char.setText(_translate("MainWindow", "Character"))
        self.character.setText(_translate("MainWindow", ""))
        self.label_char_result.setText(_translate("MainWindow", "Character Result"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
